defaults:
  - _self_
  - sim: default
  - controller: zero 

interval: 10
show: true
control_duration: 1
control_start: 0

hydra:
  job:
    chdir: true
  run:
    dir: ./logs/run/${now:%m-%d-%H-%M-%S}/
